# Generated by Django 3.0.5 on 2020-07-03 14:21

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('post_choice', models.CharField(choices=[('Boast', 'Boast'), ('Roast', 'Roast')], default='Boast', max_length=6)),
                ('score', computed_property.fields.ComputedIntegerField(compute_from='get_score', editable=False)),
            ],
        ),
    ]
